server:
  port: 7002


#Eureka配置
eureka:
  instance:
    hostname: localhost
    instance-id: eureka7002
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka/

spring:
  application:
    name: eureka-7002