server:
  port: 8003

spring:
  application:
    name: provider
  datasource:
    url: jdbc:mysql://47.115.172.160:3306?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: van
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

#整合mybatis
mybatis:
  type-aliases-package: com.van.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7002/eureka/,http://localhost:7001/eureka/
  instance:
    instance-id: MyProvider-8003