spring:
  profiles:
    active: dev

---

server:
  port: 5002
spring:
  profiles: dev
  application: 
    name: config-dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

---

server:
  port: 5003
spring:
  profiles: sit
  application:
    name: config-sit
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/